dist: trusty
sudo: required
language: go

go:
- 1.9

services:
- docker

install:
- true

script:
- go test -cpu=2 -race -v -covermode=atomic $(go list ./... | grep -v /vendor/)

after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io
 - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o kube-plex github.com/boxroxio/kube-plex
 - docker build -t quay.io/tonykhbo/custom-kube-plex:${TRAVIS_COMMIT:0:7} .
 - docker tag -f quay.io/tonykhbo/custom-kube-plex:${TRAVIS_COMMIT:0:7} "quay.io/tonykhbo/custom-kube-plex:latest"
 - docker push quay.io/tonykhbo/custom-kube-plex:latest
 - docker push quay.io/tonykhbo/custom-kube-plex:${TRAVIS_COMMIT:0:7}
