claimToken: claim-yrJB8_NoTTvp35B4vVa_ # Replace `<CLAIM_TOKEN>` by the token obtained previously.

image:
  repository: linuxserver/plex
  tag: latest
  pullPolicy: IfNotPresent

kubePlex:
  enabled: true # kubePlex (transcoder job) is disabled because not available on ARM. The transcoding will be performed by the main Plex instance instead of a separate Job.

timezone: America/NewYork

service:
  type: LoadBalancer # We will use a LoadBalancer to obtain a virtual IP that can be exposed to Plex Media via our router
  port: 32400 # Port to expose Plex

rbac:
  create: true

nodeSelector: {}

persistence:
  transcode:
    claimName: "media-ssd"
    subPath: plex/transcode
    enabled: true
  data:
    claimName: "media-ssd"
    subPath: library/
  config:
    claimName: "media-ssd"
    subPath: plex/config

resources: {}
podAnnotations: {}
proxy:
  enable: false